version: '3.2'
services:
  back:
    build: .
    ports:
      - 8079:8079
    command: mvn clean install -Dmaven.test.skip=true spring-boot:run
    volumes:
      - type: bind
        source: .
        target: /Project/
        bind:
          propagation: share
      - "/home/.m2"
      - type: bind
        source: ./front/dist/static
        target: /Project/src/main/resources/static
        bind:
          propagation: share
      - type: bind
        source: ./front/dist/index.html
        target: /Project/src/main/resources/index.html
        bind:
          propagation: share
