version: '3.2'
services:
  back:
    build: .
    ports:
      - 8079:8079
    command: mvn clean install -Dmaven.test.skip=true spring-boot:run
    volumes:
      - type: bind
        source: .
        target: /Project/
        bind:
          propagation: share
      - "/home/.m2"